# 배열 슬라이싱: 하위 배열에 접근하기

In [2]:
import numpy as np
x= np.arange(10)
print(x)
x

[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
x[:5] 

array([0, 1, 2, 3, 4])

In [6]:
x[5:]

array([5, 6, 7, 8, 9])

In [7]:
x[4:7]

array([4, 5, 6])

In [8]:
x[::2]

array([0, 2, 4, 6, 8])

In [9]:
x[1::2]

array([1, 3, 5, 7, 9])

In [10]:
x[::-1] #모든 요소를 거꾸로 나열

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [11]:
x[5::-2]

array([5, 3, 1])

In [2]:
x2=np.random.randint(10, size=(5,6)) 
x2

array([[3, 0, 4, 2, 8, 3],
       [9, 4, 9, 7, 5, 3],
       [2, 3, 9, 2, 9, 6],
       [1, 0, 6, 6, 0, 2],
       [2, 3, 2, 3, 1, 3]])

In [3]:
x3=np.random.randint(3,10, size=(5,6)) #(최소, 최대) 정수 return
x3

array([[3, 7, 3, 4, 8, 7],
       [4, 7, 9, 8, 7, 3],
       [9, 3, 3, 5, 6, 8],
       [9, 5, 6, 7, 8, 8],
       [8, 3, 6, 4, 8, 4]])

In [36]:
x2[:2, :3] #두 개의 행, 세 개의 열

array([[3, 3, 1],
       [1, 7, 3]])

In [37]:
x2[:5, ::2] #모든 행, 한 열 걸어 하나씩

array([[3, 1, 4],
       [1, 3, 0],
       [3, 5, 3],
       [8, 5, 7],
       [7, 2, 6]])

In [38]:
x2[::2, ::] #행을 하나씩 걸러 

array([[3, 3, 1, 0, 4, 0],
       [3, 1, 5, 0, 3, 6],
       [7, 3, 2, 8, 6, 6]])

In [39]:
x2

array([[3, 3, 1, 0, 4, 0],
       [1, 7, 3, 9, 0, 0],
       [3, 1, 5, 0, 3, 6],
       [8, 6, 5, 2, 7, 3],
       [7, 3, 2, 8, 6, 6]])

In [40]:
x2[::-1, ::] #행을 거꾸로

array([[7, 3, 2, 8, 6, 6],
       [8, 6, 5, 2, 7, 3],
       [3, 1, 5, 0, 3, 6],
       [1, 7, 3, 9, 0, 0],
       [3, 3, 1, 0, 4, 0]])

In [41]:
x2[::, ::-1] #열을 거꾸로 

array([[0, 4, 0, 1, 3, 3],
       [0, 0, 9, 3, 7, 1],
       [6, 3, 0, 5, 1, 3],
       [3, 7, 2, 5, 6, 8],
       [6, 6, 8, 2, 3, 7]])

In [42]:
x2[::-1, ::-1] # 차원도 거꾸로

array([[6, 6, 8, 2, 3, 7],
       [3, 7, 2, 5, 6, 8],
       [6, 3, 0, 5, 1, 3],
       [0, 0, 9, 3, 7, 1],
       [0, 4, 0, 1, 3, 3]])

In [43]:
x2

array([[3, 3, 1, 0, 4, 0],
       [1, 7, 3, 9, 0, 0],
       [3, 1, 5, 0, 3, 6],
       [8, 6, 5, 2, 7, 3],
       [7, 3, 2, 8, 6, 6]])

In [44]:
print(x2[:,0]) #x2의 첫번째 열

[3 1 3 8 7]


In [45]:
print(x2[0, :]) #x2의 첫번째 행

[3 3 1 0 4 0]


In [46]:
print(x2[0]) #행에 접근할 때는 빈 슬라이스를 생략할 수 있다.

[3 3 1 0 4 0]


# Fancy indexing: Boolean 방식 행렬 인덱싱
인덱스의 크기가 행렬의 크기와 같아야 하며, True만 선택

In [48]:
a= np.array([0,1,2,3,4,5,6,7,8,9])
idx = np.array([True, False,True, False,True, False,True, False,True, False])
print(a[idx])

[0 2 4 6 8]


## Fancy indexing: 정수 방식 행렬 인덱싱
인덱스의 크기가 행렬의 크기와 달라도 되며, 지정된 위치의 원소만 선택

In [51]:
a= np.array([0,1,2,3,4,5,6,7,8,9])*10
idx = np.array([0,2,4,6,8])
print(a[idx])

[ 0 20 40 60 80]


중복되는 인덱스도 가능함

In [53]:
a= np.array([0,1,2,3])*10
idx = np.array([0,0,0,2,2,2,2,3,3,3,3,3])
print(a[idx])

[ 0  0  0 20 20 20 20 30 30 30 30 30]


In [54]:
x=np.arange(10)
idx=np.array([2,1,8,4])
x[idx] = 999
print(x)

[  0 999 999   3 999   5   6   7 999   9]


In [55]:
x[idx] -= 20 #할당 연산자 사용 가능
print(x)

[  0 979 979   3 979   5   6   7 979   9]


# 배열 슬라이스는 배열 데이터의 copy가 아니라 view를 반환한다

In [41]:
x3= np.random.randint(10, size=(3,4))
print(x3)

[[5 4 9 6]
 [5 7 1 1]
 [0 2 5 3]]


In [44]:
x3_sub =x3[:2, :2] #콤마사용해서 행 0,1 열 0,1 슬라이싱
print(x3_sub)

[[5 4]
 [5 7]]


In [46]:
x3_sub[0,0]=99 #콤마 사용 인덱싱 가능
print(x3_sub)

[[99  4]
 [ 5  7]]


In [53]:
print(x3) #x3도 같이 바뀜

[[99  4  9  6]
 [ 5  7  1  1]
 [ 0  2  5  3]]


In [54]:
x3_sub_copy =x3[:2,:2].copy() #copy method로 처리하면 새로운 ndarray만들어짐
print(x3_sub_copy)

[[99  4]
 [ 5  7]]


In [55]:
x3_sub_copy[0,0]=33
print(x3_sub_copy)

[[33  4]
 [ 5  7]]


In [56]:
print(x3) #x3 바뀌지 않음

[[99  4  9  6]
 [ 5  7  1  1]
 [ 0  2  5  3]]


# ndarray 할당은 참조만 전달

In [10]:
x=np.array([1,2,3,4])
o = x #할당
print(id(o), id(x)) #같은 id

2413251355632 2413251355632


In [11]:
o_sub = x[1:3]
print(o_sub)
print(id(o_sub))

[2 3]
2413251356832


In [12]:
o_sub[0] =99 # slicing과 원본이 같이 바뀜
print(o_sub, x)

[99  3] [ 1 99  3  4]


In [13]:
o_copy =x.copy()
print(id(o_copy), id(x))
o_copy[1] =77
print(o_copy, x)

2413251357312 2413251355632
[ 1 77  3  4] [ 1 99  3  4]


# 배열 원소 개수 

In [15]:
import numpy as np
npa = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(npa)
print(npa.size, npa.shape, npa.ndim, len(npa))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9 (3, 3) 3


In [17]:
np1a = np.array([1, 999, 11, 23, 45, 45, 31])
print(np1a)
print(np1a.size, np1a.shape, np1a.ndim, len(np1a))

[  1 999  11  23  45  45  31]
7 (7,) 1 7


In [26]:
pyL = range(1,10)
print(type(pyL), pyL)

<class 'range'> range(1, 10)


In [22]:
npA =np.arange(1,10, dtype=np.float)
print(type(npA), npA)

<class 'numpy.ndarray'> [ 1.  2.  3.  4.  5.  6.  7.  8.  9.]


In [23]:
npA =np.arange(1,10, dtype=np.int)
print(type(npA), npA)

<class 'numpy.ndarray'> [1 2 3 4 5 6 7 8 9]


# 연산방식

In [30]:
cvalues = [25.3, 24.8, 26.9, 23.9]
c = np.array(cvalues)
print(c)
F = c * 9/5 +32
print(type(F), F)

[ 25.3  24.8  26.9  23.9]
<class 'numpy.ndarray'> [ 77.54  76.64  80.42  75.02]


기존 방식, list comprehension으로 loop문 실행

In [31]:
pyF = [x *9/5 +32 for x in cvalues]
print(type(pyF), pyF)

<class 'list'> [77.54, 76.64, 80.42, 75.02]


In [33]:
%%timeit
F = c * 9/5 +32
print(type(F), F)

<class 'numpy.ndarray'> [ 77.54  76.64  80.42  75.02]
<class 'numpy.ndarray'> [ 77.54  76.64  80.42  75.02]
<class 'numpy.ndarray'> [ 77.54  76.64  80.42  75.02]
<class 'numpy.ndarray'> [ 77.54  76.64  80.42  75.02]
<class 'numpy.ndarray'> [ 77.54  76.64  80.42  75.02]
<class 'numpy.ndarray'> [ 77.54  76.64  80.42  75.02]
<class 'numpy.ndarray'> [ 77.54  76.64  80.42  75.02]
<class 'numpy.ndarray'> [ 77.54  76.64  80.42  75.02]
<class 'numpy.ndarray'> [ 77.54  76.64  80.42  75.02]
<class 'numpy.ndarray'> [ 77.54  76.64  80.42  75.02]
<class 'numpy.ndarray'> [ 77.54  76.64  80.42  75.02]
<class 'numpy.ndarray'> [ 77.54  76.64  80.42  75.02]
<class 'numpy.ndarray'> [ 77.54  76.64  80.42  75.02]
<class 'numpy.ndarray'> [ 77.54  76.64  80.42  75.02]
<class 'numpy.ndarray'> [ 77.54  76.64  80.42  75.02]
<class 'numpy.ndarray'> [ 77.54  76.64  80.42  75.02]
<class 'numpy.ndarray'> [ 77.54  76.64  80.42  75.02]
<class 'numpy.ndarray'> [ 77.54  76.64  80.42  75.02]
<class 'numpy.ndarray'> [ 77

In [32]:
%%timeit
pyF = [x *9/5 +32 for x in cvalues]
print(type(pyF), pyF)

<class 'list'> [77.54, 76.64, 80.42, 75.02]
<class 'list'> [77.54, 76.64, 80.42, 75.02]
<class 'list'> [77.54, 76.64, 80.42, 75.02]
<class 'list'> [77.54, 76.64, 80.42, 75.02]
<class 'list'> [77.54, 76.64, 80.42, 75.02]
<class 'list'> [77.54, 76.64, 80.42, 75.02]
<class 'list'> [77.54, 76.64, 80.42, 75.02]
<class 'list'> [77.54, 76.64, 80.42, 75.02]
<class 'list'> [77.54, 76.64, 80.42, 75.02]
<class 'list'> [77.54, 76.64, 80.42, 75.02]
<class 'list'> [77.54, 76.64, 80.42, 75.02]
<class 'list'> [77.54, 76.64, 80.42, 75.02]
<class 'list'> [77.54, 76.64, 80.42, 75.02]
<class 'list'> [77.54, 76.64, 80.42, 75.02]
<class 'list'> [77.54, 76.64, 80.42, 75.02]
<class 'list'> [77.54, 76.64, 80.42, 75.02]
<class 'list'> [77.54, 76.64, 80.42, 75.02]
<class 'list'> [77.54, 76.64, 80.42, 75.02]
<class 'list'> [77.54, 76.64, 80.42, 75.02]
<class 'list'> [77.54, 76.64, 80.42, 75.02]
<class 'list'> [77.54, 76.64, 80.42, 75.02]
<class 'list'> [77.54, 76.64, 80.42, 75.02]
<class 'list'> [77.54, 76.64, 80

# 내부 원소 접근방식: __getitem__ &  __setitem__

In [70]:
pyl=range(1,10)
print(type(pyl), pyl)
npa=np.arange(1,10,dtype=np.float_)
print(type(npa), npa)
idx=np.array([True, False,True, False,True, False,True, False,True])
print(idx.dtype, idx)

<class 'range'> range(1, 10)
<class 'numpy.ndarray'> [ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
bool [ True False  True False  True False  True False  True]


In [71]:
print(pyl.__getitem__(2))
print(npa.__getitem__(2))
print(npa.__getitem__(idx))

3
3.0
[ 1.  3.  5.  7.  9.]


In [72]:
npa.__setitem__(1,200)
print(npa)
npa.__setitem__(idx,222)
print(npa)

[   1.  200.    3.    4.    5.    6.    7.    8.    9.]
[ 222.  200.  222.    4.  222.    6.  222.    8.  222.]


In [59]:
print(x.reshape((3,1)))
print(x)

[[1]
 [2]
 [3]]
[1 2 3]


In [7]:
# 함수와 메서드를 동일하게 처리한다는 것인데, 이전의 얘기인 것 같음
def add(self,x,y): #함수 정의
    return x+y
class A(object): #클래스 정의에 외부 함수 이용
    add= add
    
a = A()
print(a.add(5,5), type(a.add))
print(add(a,5,5), type(add))

10 <class 'method'>
10 <class 'function'>


In [6]:
npa =np.array([1,2,3.0])
print(npa)
s = open("arrayTest.nd", "wb")
np.save(s, npa)
#%ls
s= open("arrayTest.nd","rb" )
ndx = np.load(s)
print(ndx)
#s.seek(0)
print(s.read())

[1. 2. 3.]
[1. 2. 3.]
b''
